version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    restart: always
    command: [
      "poetry", "run", "python3", "-m", "bot"
    ]

networks:
  default:
    driver: bridge
